### ISSUE TITLE
「色彩管理」底下的「查看」建議改成「風格」

### ISSUE THREAD

**Issue by qwwqe** [l10n-tw/blender-branches-tw#9]
英文版的Look好像是名詞，像look and feel，與其翻成「查看」或許翻「風格」會比較貼切英文的語意，對使用者而言也更能傳達這項選項的用途。

**Comment by zerng07** [comment]
https://weblate.slat.org/translate/blender/blender/zh_Hant/?checksum=25ec4e0650243de0
感謝回報，已先採納。待回傳上游後關閉本 issue。

**Comment by zerng07** [comment]
merged with https://github.com/l10n-tw/blender-branches-tw/pull/10

**Comment by zerng07** [comment]
Updated to upstream svn.
